language: go

go:
  - 1.6
  - 1.7
  - 1.8
  - tip
env:
  - LIBWEBP_VERSION="0.5.0"
  - LIBWEBP_VERSION="0.5.1"
  - LIBWEBP_VERSION="1.1.0"


cache:
  directories:
    - $HOME/cache
sudo: false

before_install:
  - LIBWEBP_PREFIX=$HOME/cache/libwebp-${LIBWEBP_VERSION} make libwebp
  - cd $HOME/gopath/src/github.com/harukasan/go-libwebp
  - export CGO_CFLAGS="-I $HOME/cache/libwebp-${LIBWEBP_VERSION}/include"
  - export CGO_LDFLAGS="-L $HOME/cache/libwebp-${LIBWEBP_VERSION}/lib"
  - export LD_LIBRARY_PATH=$HOME/cache/libwebp-${LIBWEBP_VERSION}/lib:$LD_LIBRARY_PATH
